Upstream changes (#1842)
* Upstream hotfixes

* Set peekSize defaults

* Remove debug logs

* Update queue.go

* Create partitions during lease

* Undo partition creation

* fix compilation errors in queue_test.go

* lint: remove unused code (func (*queue).ewmaPeekSize in pkg/execution/state/redis_state/queue_processor.go:1016)

* remove unused code (func (*queue).ewmaPeekSize in pkg/execution/state/redis_state/queue_processor.go:1016)

* minor: rename unused args

* use clamped peek min/max values in queue.peekSize

* wip

* reintroduce ewma

we want to keep this, even if it's unused right now

* Update queue_processor.go

* Refactor key queue disable logic

* Update queue_test.go

* Fix tests

* golint

* Update queue.go

* run dev server in partition-only mode

* Improve tests regarding concurrency requeue

---------

Co-authored-by: Chris Dzombak <chris@inngest.com>
Co-authored-by: Tony Holdstock-Brown <tonyhb@gmail.com>